# Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.8'

services:
  tallarna-hackathon-mysql:
    image: mysql
    container_name: ${COMPOSE_PROJECT_NAME?}-MySQL-DB
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: tallarna_hackathon
      MYSQL_ROOT_PASSWORD: password
    user: "1000:1000"
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql

